a = input('Digte algo: ')
print('O tipo primitivo é:', type(a))
print('Só tem espaços?', a.isspace())
print('É número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Tudo maiúsculo?', a.isupper())
print('Tudo minúsculo?', a.islower())
print('É capitalizada?', a.istitle())